### ISSUE TITLE
instaling openblas on mac

### ISSUE THREAD

**Issue by ybrandvain** [DReichLab/AdmixTools#80] opened 2021-06-19 03:01 UTC
for some mac users 

"brew install homebrew/science/openblas" will not work and therefore the makefile will error out
point them to "brew install --build-from-source openblas"

**Comment by MatthewMah** [comment] 2021-06-22 15:36
This was caused by a regression from 6831501f9967270cbb4e7fa2e13d6a7cc41f2be5 and fixed in 4c3f5fd191322db734e0e238e9f98696f3f26907.

**Closed by MatthewMah** 2021-06-22 15:36 UTC
